apiVersion: v1
kind: ConfigMap
metadata:
  name: ${KUBE_APPLICATION}-nginx-webroot
  namespace: ${KUBE_NAMESPACE}
data:
  index.php: |
    <?php
    echo "Nginx";

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${KUBE_APPLICATION}-nginx-config
  namespace: ${KUBE_NAMESPACE}
data:
  proxy-body-size: "64m"
  proxy-connect-timeout: "60"
  proxy-read-timeout: "120"
  proxy-send-timeout: "120"
  app.conf: |
    upstream app_server {
        server 127.0.0.1:9000;
    }
    log_format trebono '$remote_addr - $remote_user [$time_local] "$request" '
                     '$status $body_bytes_sent "$http_referer" "$http_user_agent" '
                     '"$http_x_forwarded_for" $request_id';
    server {
        listen      80;
        listen [::]:80;
        add_header X-Request-ID $request_id;
        # access_log /var/log/nginx/access.log trebono;

        server_name localhost;
        root        /app/htdocs;

       location / {
            try_files $uri $uri/ /index.php?$query_string;

            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_index index.php;

            fastcgi_pass app_server;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param X_REQUEST_ID $request_id;
        }
    }
